
["Artisanal Configs"]
	# If true, animals drop generic animal fat items,
	# and non-generic animal fats can be crafted into their generic ones.
	# If false, animals drop their species-specific animal fats.
	genericAnimalFat = false
	# If true, enables the barrel recipe in which Flux can be
	# mixed with water to make Slaked Lime
	fluxMakesLimewater = false

