#How many bark pieces to drop per side
#Default: 1
#Range: 0 ~ 64
barkDropCount = 1
#How many bast pieces to drop per side
#Default: 1
#Range: 0 ~ 64
bastDropCount = 1
#How much sawdust should drop from each saw interaction
#Default: 1
#Range: 0 ~ 64
sawdustDropCount = 1
#How many support should be crafted from one debarked half
#Default: 4
#Range: 0 ~ 64
supportPerLogHalf = 4
#How many lumber should be crafted from one debarked quarter
#Default: 2
#Range: 0 ~ 64
lumberPerLogQuarter = 2
#How many fences should drop from each plank interaction
#Default: 2
#Range: 0 ~ 64
fenceFromPlank = 2
#How many fences should drop from each stair interaction
#Default: 2
#Range: 0 ~ 64
fenceFromStair = 2
#How many log fences should drop from each log interaction
#Default: 4
#Range: 0 ~ 64
fenceFromLog = 4
#How many trapdoors should drop from each slab interaction
#Default: 2
#Range: 0 ~ 64
trapdoorFromSlab = 2
#How many logs can custom log pile store per slot
#Default: 4
#Range: 1 ~ 64
logPileLogCapacity = 4
#How many log halves can custom log pile store per slot
#Default: 8
#Range: 1 ~ 64
logPileLogHalfCapacity = 8
#How many log quarters can custom log pile store per slot
#Default: 16
#Range: 1 ~ 64
logPileLogQuarterCapacity = 16
#How many log quarters can custom log pile store in total across all slots
#Maximum of 1792 is achieved when all slots are configured to hold 64 items
#Default: 64
#Range: 1 ~ 1792
logPileLimit = 64
#Should the custom wood projectile be shot instead of a ItemEntity
#Default: true
logProjectileVsItem = true
#Cooldown on tools after log interaction succeeded
#Level 0: IGNEOUS_INTRUSIVE, IGNEOUS_EXTRUSIVE, SEDIMENTARY, METAMORPHIC
#Level 1: COPPER
#Level 2: BRONZE, BISMUTH_BRONZE, BLACK_BRONZE
#Level 3: WROUGHT_IRON
#Level 4: STEEL
#Level 5: BLACK_STEEL
#Level 6: BLUE_STEEL, RED_STEEL
#Default: [10, 10, 10, 10, 10, 10, 10]
#Range: [0, 1200]
toolCooldowns = [10, 10, 10, 10, 10, 10, 10]

